export const ANGULAR_NEWS_INIT = 'ANGULAR_NEWS_INIT'
export const ANGULAR_NEWS_SUCCESS = 'ANGULAR_NEWS_SUCCESS'
export const ANGULAR_NEWS_ERROR = 'ANGULAR_NEWS_ERROR'

export const REACT_NEWS_INIT = 'REACT_NEWS_INIT'
export const REACT_NEWS_SUCCESS = 'REACT_NEWS_SUCCESS'
export const REACT_NEWS_ERROR = 'REACT_NEWS_ERROR'

export const VUE_NEWS_INIT = 'VUE_NEWS_INIT'
export const VUE_NEWS_SUCCESS = 'VUE_NEWS_SUCCESS'
export const VUE_NEWS_ERROR = 'VUE_NEWS_ERROR'
